---
- name: php | Install PHP Packages including fpm
  apt: pkg={{ item }} state=latest
  with_items:
  - php5
  - php5-cli 
  - php5-fpm
  - php5-dev 
  - php5-mcrypt 
  - php5-curl 
  - php5-gd
  - php5-mysql

- name: PHP | php5-fpm php.ini set pathinfo = 0
  lineinfile: dest=/etc/php5/fpm/php.ini regexp='^cgi.fix_pathinfo = 1' line='cgi.fix_pathinfo = 0' backup=yes
